import os
import sys
import re
import json
import argparse
import requests

COMMON_SECRET_PATTERNS = [
    (r'(?i)(?:aws_access_key_id|aws_secret_access_key|aws_session_token)\s*=\s*["\']?([A-Za-z0-9/+=]{20,})', "AWS Credential Leak"),
    (r'(?i)(?:ghp|gho|ghu|ghs|ghr)_[A-Za-z0-9_]{36,}', "GitHub Personal Access Token"),
    (r'-----BEGIN\s+([A-Z\s]+)?PRIVATE\s+KEY-----', "Exposed Private Key"),
    (r'(?i)(?:api[_-]?key|secret[_-]?key|auth[_-]?token)\s*=\s*["\']([a-zA-Z0-9_\-]{16,})["\']', "Potential Hardcoded API Key/Token"),
    (r'(?i)password\s*=\s*["\']([^"\']{4,})["\']', "Hardcoded Plaintext Password"),
]

LANGUAGE_VULN_PATTERNS = [
    (r'(?i)(?:eval|exec)\s*\(', "Dangerous Dynamic Code Execution (eval/exec)"),
    (r'(?i)subprocess\.(?:Popen|call|run)\s*\(.*shell\s*=\s*True', "Command Injection Risk (shell=True)"),
    (r'(?i)dangerouslySetInnerHTML', "Cross-Site Scripting (XSS) via dangerouslySetInnerHTML"),
    (r'(?i)pickle\.loads\s*\(', "Insecure Deserialization (pickle.loads)"),
]

def mask_sensitive_value(line: str) -> str:
    # Che giấu phần giữa của các chuỗi token/key dài để bảo mật
    def mask_match(m):
        val = m.group(0)
        if len(val) > 8:
            return val[:4] + "..." + val[-4:]
        return val
    return re.sub(r'[A-Za-z0-9_\-]{12,}', mask_match, line)

def get_pr_diff(repo_full_name: str, pr_number: int, github_token: str) -> str:
    url = f"https://api.github.com/repos/{repo_full_name}/pulls/{pr_number}"
    headers = {"Authorization": f"Bearer {github_token}", "Accept": "application/vnd.github.v3.diff"}
    res = requests.get(url, headers=headers, timeout=30)
    return res.text if res.status_code == 200 else ""

def post_comment(repo_full_name: str, pr_number: int, github_token: str, body: str) -> bool:
    url = f"https://api.github.com/repos/{repo_full_name}/issues/{pr_number}/comments"
    headers = {"Authorization": f"Bearer {github_token}", "Accept": "application/vnd.github.v3+json"}
    res = requests.post(url, headers=headers, json={"body": body}, timeout=30)
    return res.status_code == 201

def heuristic_scan(diff_text: str) -> list:
    findings = []
    for line in diff_text.splitlines():
        if line.startswith('+') and not line.startswith('+++'):
            clean_line = line[1:].strip()
            masked_line = mask_sensitive_value(clean_line)
            for pattern, desc in COMMON_SECRET_PATTERNS:
                if re.search(pattern, line):
                    findings.append(f"- **[CRITICAL SECRET LEAK]** `{desc}`: `{masked_line[:80]}`")
            for pattern, desc in LANGUAGE_VULN_PATTERNS:
                if re.search(pattern, line):
                    findings.append(f"- **[HIGH SECURITY RISK]** `{desc}`: `{masked_line[:80]}`")
    return findings

def install_git_hook():
    hook_config = """# Auto-generated by codex-security-linter
repos:
  - repo: https://github.com/knmt1219/codex-security-linter
    rev: v1.5.0
    hooks:
      - id: codex-security-linter
"""
    with open(".pre-commit-config.yaml", "w", encoding="utf-8") as f:
        f.write(hook_config)
    print("✅ Successfully generated .pre-commit-config.yaml for your repository!")

def export_sarif(findings: list, output_path: str = "results.sarif"):
    sarif_data = {
        "$schema": "https://raw.githubusercontent.com/oasis-tcs/sarif-spec/master/Schemata/sarif-schema-2.1.0.json",
        "version": "2.1.0",
        "runs": [{
            "tool": {
                "driver": {
                    "name": "Codex Security Linter",
                    "version": "1.5.0",
                    "informationUri": "https://github.com/knmt1219/codex-security-linter",
                    "rules": [{
                        "id": "CSL001",
                        "name": "SecurityVulnerabilityOrSecret",
                        "shortDescription": {"text": "Security flaw or secret detected in code changes"}
                    }]
                }
            },
            "results": [
                {
                    "ruleId": "CSL001",
                    "level": "error" if "CRITICAL" in f or "HIGH" in f else "warning",
                    "message": {"text": f}
                } for f in findings
            ]
        }]
    }
    with open(output_path, "w", encoding="utf-8") as f:
        json.dump(sarif_data, f, indent=2)
    print(f"SARIF report exported to: {output_path}")

def audit_diff_with_ai(diff_text: str, api_key: str, model_name: str = "gpt-4o-mini") -> str:
    try:
        from openai import OpenAI
    except ImportError:
        return "*(OpenAI SDK not installed. Please run `pip install openai` to enable AI vulnerability analysis)*"

    client = OpenAI(api_key=api_key)
    prompt = (
        "You are an application security expert auditing an open-source Pull Request.\n"
        "Analyze the following code diff and report:\n"
        "1. [SEVERITY: CRITICAL/HIGH/MEDIUM/LOW] Summary of found risks (Secret leaks, SQLi, XSS, RCE, Insecure Deserialization).\n"
        "2. Concrete remediation code patches formatted as GitHub suggestions (```suggestion ... ```) when applicable.\n"
        "3. Best practices recommendation.\n"
        "If no vulnerabilities are detected, state: 'No security vulnerabilities detected.'\n\n"
        f"Diff:\n```diff\n{diff_text[:12000]}\n```"
    )
    res = client.chat.completions.create(
        model=model_name,
        messages=[
            {"role": "system", "content": "You are a specialized security audit agent for open-source repositories."},
            {"role": "user", "content": prompt}
        ],
        temperature=0.1,
    )
    return res.choices[0].message.content

def main():
    parser = argparse.ArgumentParser(description="Codex Security Linter CLI & GitHub Action")
    parser.add_argument("--local", action="store_true", help="Run scan on local git diff")
    parser.add_argument("--sarif", type=str, help="Export scan results to SARIF format")
    parser.add_argument("--strict", action="store_true", help="Fail with exit code 1 if critical/high risks found")
    parser.add_argument("--install-hook", action="store_true", help="Auto-install pre-commit configuration")
    args = parser.parse_args()

    if args.install_hook:
        install_git_hook()
        return

    api_key = os.environ.get("OPENAI_API_KEY", "").strip()
    model_name = os.environ.get("MODEL_NAME", "gpt-4o-mini")

    if args.local:
        diff_text = os.popen("git diff HEAD~1").read()
        if not diff_text.strip():
            diff_text = os.popen("git diff").read()
        if not diff_text.strip():
            print("No local git changes detected to audit.")
            return

        print("🔍 Running Heuristic & Language-Aware Security Scan...")
        findings = heuristic_scan(diff_text)
        if findings:
            print("\n⚠️ Scan Findings:")
            for f in findings:
                print(f"  {f}")
            if args.sarif:
                export_sarif(findings, args.sarif)
            if args.strict:
                print("\n❌ Strict mode: Vulnerabilities detected. Exiting with error.")
                sys.exit(1)
        else:
            print("✅ Heuristic Scan: Clean (No secrets or dangerous patterns detected)")

        if api_key:
            print("\n🤖 Running Deep AI Security Analysis...")
            ai_report = audit_diff_with_ai(diff_text, api_key, model_name)
            print("\n" + ai_report)
        else:
            print("\nℹ️ Tip: Set OPENAI_API_KEY for advanced AI vulnerability analysis.")
        return

    # Chế độ GitHub Action
    token = os.environ.get("GITHUB_TOKEN")
    event_path = os.environ.get("GITHUB_EVENT_PATH")
    if not (token and event_path):
        print("Warning: GITHUB_TOKEN or GITHUB_EVENT_PATH not set. Exiting cleanly.")
        return

    try:
        with open(event_path, "r", encoding="utf-8") as f:
            event_data = json.load(f)
    except Exception as e:
        print(f"Error loading event payload: {e}")
        return

    pr_data = event_data.get("pull_request")
    if not pr_data:
        print("Not a pull request event.")
        return

    repo_full_name = event_data["repository"]["full_name"]
    pr_number = pr_data["number"]
    diff_text = get_pr_diff(repo_full_name, pr_number, token)

    if not diff_text.strip():
        print("Empty or inaccessible diff.")
        return

    findings = heuristic_scan(diff_text)
    report_sections = []

    if findings:
        report_sections.append("#### 🚨 Immediate Risks Detected (Heuristic Engine)\n" + "\n".join(findings))
        if args.sarif:
            export_sarif(findings, args.sarif)

    if api_key:
        try:
            ai_report = audit_diff_with_ai(diff_text, api_key, model_name)
            report_sections.append("#### 🤖 Deep AI Security Analysis\n" + ai_report)
        except Exception as e:
            report_sections.append(f"*(AI analysis unavailable: {e})*")
    else:
        report_sections.append("ℹ️ *Note: Add `OPENAI_API_KEY` to repository secrets to enable deep AI vulnerability analysis and One-Click suggestions.*")

    final_comment = (
        "### 🛡️ Codex Security Audit Report\n\n"
        + "\n\n".join(report_sections)
        + "\n\n---\n*Automated audit powered by [codex-security-linter](https://github.com/knmt1219/codex-security-linter)*"
    )

    post_comment(repo_full_name, pr_number, token, final_comment)
    print("Security audit executed and posted successfully.")

    if args.strict and findings:
        sys.exit(1)

if __name__ == "__main__":
    main()
