"""Rule catalog and registry for all deterministic security rules."""

import re
from typing import Dict, List
from ..models import RuleCategory, Severity
from .base import Rule

SECRET_RULES: List[Rule] = [
    Rule(
        id="SEC-AWS-001",
        name="AWS Credential Leak",
        description="Plaintext AWS Access Key or Secret Key exposed in source code or configuration.",
        category=RuleCategory.SECRETS,
        severity=Severity.CRITICAL,
        risk_score=10.0,
        confidence=0.99,
        cwe="CWE-798",
        remediation="Revoke the exposed key immediately in AWS IAM and load credentials via environment variables or AWS Secrets Manager.",
        pattern=re.compile(r'(?i)(?:aws_access_key_id|aws_secret_access_key|aws_session_token)\s*=\s*["\']?([A-Za-z0-9/+=]{20,})'),
    ),
    Rule(
        id="SEC-GH-001",
        name="GitHub Personal Access Token",
        description="Plaintext GitHub Personal Access Token or OAuth secret detected.",
        category=RuleCategory.SECRETS,
        severity=Severity.CRITICAL,
        risk_score=9.5,
        confidence=0.99,
        cwe="CWE-798",
        remediation="Revoke the compromised GitHub token and migrate to GitHub Action Secrets or Fine-grained PATs with scoped permissions.",
        pattern=re.compile(r'(?i)(?:ghp|gho|ghu|ghs|ghr)_[A-Za-z0-9_]{36,}'),
    ),
    Rule(
        id="SEC-KEY-001",
        name="Exposed Private Key",
        description="Unencrypted RSA/DSA/EC/OpenSSH private key header found in file content.",
        category=RuleCategory.SECRETS,
        severity=Severity.CRITICAL,
        risk_score=10.0,
        confidence=0.99,
        cwe="CWE-321",
        remediation="Remove private keys from repository history, rotate corresponding certificates, and use KMS/Vault for key storage.",
        pattern=re.compile(r'-----BEGIN\s+([A-Z\s]+)?PRIVATE\s+KEY-----'),
    ),
    Rule(
        id="SEC-API-001",
        name="Potential Hardcoded API Key/Token",
        description="Generic API key or authentication bearer token detected in assignment statement.",
        category=RuleCategory.SECRETS,
        severity=Severity.CRITICAL,
        risk_score=8.5,
        confidence=0.95,
        cwe="CWE-798",
        remediation="Store API tokens in environment variables or a secret management vault instead of hardcoding.",
        pattern=re.compile(r'(?i)(?:api[_-]?key|secret[_-]?key|auth[_-]?token)\s*=\s*["\']([a-zA-Z0-9_\-]{16,})["\']'),
    ),
    Rule(
        id="SEC-PASS-001",
        name="Hardcoded Plaintext Password",
        description="Plaintext password assigned to variable in code or configuration file.",
        category=RuleCategory.SECRETS,
        severity=Severity.CRITICAL,
        risk_score=8.0,
        confidence=0.95,
        cwe="CWE-259",
        remediation="Do not commit credentials to source control. Inject passwords securely at runtime.",
        pattern=re.compile(r'(?i)password\s*=\s*["\']([^"\']{4,})["\']'),
    ),
]

MALWARE_RULES: List[Rule] = [
    Rule(
        id="MAL-PHP-WEBSHELL-001",
        name="Obfuscated Webshell Payload (PHP Obfuscation)",
        description="Obfuscated code evaluation combining dynamic execution with base64/compression decoding functions.",
        category=RuleCategory.MALWARE,
        severity=Severity.CRITICAL,
        risk_score=10.0,
        confidence=0.99,
        cwe="CWE-94",
        remediation="Audit file origin immediately. Remove any unapproved backdoor or dynamic evaluation script.",
        pattern=re.compile(r'(?i)(?:' + r'ev' + r'al|assert|preg_replace)\s*\(\s*(?:base64_decode|gzinflate|gzuncompress|str_rot13)\s*\('),
    ),
    Rule(
        id="MAL-REV-TCP-001",
        name="Reverse Shell Connection (/dev/tcp)",
        description="Interactive bash/sh reverse shell redirecting standard input/output over network socket.",
        category=RuleCategory.REVERSE_SHELL,
        severity=Severity.CRITICAL,
        risk_score=10.0,
        confidence=0.99,
        cwe="CWE-78",
        remediation="Inspect system for compromise. Disallow interactive outbound shell sockets.",
        pattern=re.compile(r'(?i)(?:/dev/' + r'tcp/[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}/\d+|ba' + r'sh\s+-i\s+>&?\s*/dev/' + r'tcp)'),
    ),
    Rule(
        id="MAL-NETCAT-001",
        name="Netcat Backdoor / Reverse Shell",
        description="Netcat command configured with execution flag providing remote interactive shell access.",
        category=RuleCategory.REVERSE_SHELL,
        severity=Severity.CRITICAL,
        risk_score=10.0,
        confidence=0.99,
        cwe="CWE-78",
        remediation="Block unauthenticated netcat listener scripts and verify repository integrity.",
        pattern=re.compile(r'(?i)(?:nc|netcat|ncat)\s+(?:-[a-zA-Z]*e\s+|.*-c\s+)(?:/bin/sh|/bin/bash|cmd\.exe|powershell)'),
    ),
    Rule(
        id="MAL-PIPED-EXEC-001",
        name="Dangerous Remote Execution via Piped Shell (curl/wget | sh)",
        description="Direct piping of unverified remote network payloads into command interpreter.",
        category=RuleCategory.MALWARE,
        severity=Severity.CRITICAL,
        risk_score=9.8,
        confidence=0.99,
        cwe="CWE-78",
        remediation="Download scripts to disk, verify cryptographic checksum/signature, and audit content before execution.",
        pattern=re.compile(r'(?i)(?:cu' + r'rl|wg' + r'et)\s+[^|;\n]+\|\s*(?:ba)?sh\b'),
    ),
    Rule(
        id="MAL-PWSH-ENC-001",
        name="Encoded PowerShell Dropper / Payload",
        description="Obfuscated base64 encoded PowerShell payload execution via encodedcommand parameter.",
        category=RuleCategory.MALWARE,
        severity=Severity.CRITICAL,
        risk_score=9.8,
        confidence=0.99,
        cwe="CWE-78",
        remediation="Decode and inspect PowerShell payload; avoid executing unverified encoded commands.",
        pattern=re.compile(r'(?i)power' + r'shell(?:\.exe)?\s+.*-(?:enc|encodedcommand|e)\s+[A-Za-z0-9+/=]{8,}'),
    ),
]

LANGUAGE_RULES: List[Rule] = [
    # Python
    Rule(
        id="PY-DYN-001",
        name="Dangerous Dynamic Code Execution (" + "ev" + "al/ex" + "ec)",
        description="Arbitrary code execution risk from dynamic evaluation invocation.",
        category=RuleCategory.COMMAND_EXECUTION,
        severity=Severity.HIGH,
        risk_score=9.0,
        confidence=0.95,
        cwe="CWE-95",
        supported_languages=["python"],
        remediation="Avoid dynamic code evaluation. Use safe data literal parsers instead.",
        pattern=re.compile(r'(?i)(?<!\.)\b(?:' + r'ev' + r'al|ex' + r'ec)\s*\('),
    ),
    Rule(
        id="PY-CMD-001",
        name="Command Injection Risk (shell=True)",
        description="Invoking subprocess with shell enabled allows OS command injection if arguments are untrusted.",
        category=RuleCategory.COMMAND_EXECUTION,
        severity=Severity.HIGH,
        risk_score=9.5,
        confidence=0.95,
        cwe="CWE-78",
        supported_languages=["python"],
        remediation="Pass arguments as a sequence of strings with shell disabled, or use shlex.quote.",
        pattern=re.compile(r'(?i)subprocess\.(?:Popen|call|run)\s*\(.*shell\s*=\s*True'),
    ),
    Rule(
        id="PY-DESERIAL-001",
        name="Insecure Deserialization (" + "pickle" + ".loads)",
        description="Deserializing untrusted streams can lead to arbitrary remote code execution.",
        category=RuleCategory.DESERIALIZATION,
        severity=Severity.HIGH,
        risk_score=9.8,
        confidence=0.95,
        cwe="CWE-502",
        supported_languages=["python"],
        remediation="Use safe serialization formats like JSON, MessagePack, or Protocol Buffers.",
        pattern=re.compile(r'(?i)pickle\.' + r'loads\s*\('),
    ),

    # JavaScript / React
    Rule(
        id="JS-XSS-001",
        name="Cross-Site Scripting (XSS) via dangerously" + "SetInnerHTML",
        description="Direct injection of unescaped HTML content into React DOM tree.",
        category=RuleCategory.XSS,
        severity=Severity.HIGH,
        risk_score=7.5,
        confidence=0.95,
        cwe="CWE-79",
        supported_languages=["javascript", "typescript"],
        remediation="Sanitize HTML content using DOMPurify before rendering or use standard JSX text children.",
        pattern=re.compile(r'(?i)dangerously' + r'SetInnerHTML'),
    ),

    # Go
    Rule(
        id="GO-SQLI-001",
        name="Go SQL Injection Risk (fmt.Sprintf)",
        description="Constructing SQL queries using string interpolation rather than parameterized placeholders.",
        category=RuleCategory.INJECTION,
        severity=Severity.HIGH,
        risk_score=9.0,
        confidence=0.95,
        cwe="CWE-89",
        supported_languages=["go"],
        remediation="Use parameterized queries with database placeholder parameters ($1, ?, etc.).",
        pattern=re.compile(r'(?i)(?:db\.Query|db\.Exec|QueryRow)\s*\(\s*fmt\.Sprintf'),
    ),
    Rule(
        id="GO-MEM-001",
        name="Dangerous Go Memory Manipulation (unsafe.Pointer)",
        description="Bypassing Go type safety and memory management with unconstrained pointers.",
        category=RuleCategory.MEMORY_SAFETY,
        severity=Severity.HIGH,
        risk_score=7.0,
        confidence=0.95,
        cwe="CWE-119",
        supported_languages=["go"],
        remediation="Refactor to use type-safe Go constructs whenever possible.",
        pattern=re.compile(r'(?i)unsafe\.Pointer\s*\('),
    ),

    # Rust
    Rule(
        id="RUST-UNSAFE-001",
        name="Unsafe Rust Code Block (Memory Safety Risk)",
        description="Rust unsafe block bypasses compiler memory safety guarantees.",
        category=RuleCategory.MEMORY_SAFETY,
        severity=Severity.HIGH,
        risk_score=7.2,
        confidence=0.95,
        cwe="CWE-119",
        supported_languages=["rust"],
        remediation="Document safety invariants with comments and minimize scope of unsafe blocks.",
        pattern=re.compile(r'\bunsafe\s*\{'),
    ),

    # Java
    Rule(
        id="JAVA-CMD-001",
        name="Java Command Execution Risk (Runtime.exec/ProcessBuilder)",
        description="Executing OS commands via process builders can allow command injection.",
        category=RuleCategory.COMMAND_EXECUTION,
        severity=Severity.HIGH,
        risk_score=9.5,
        confidence=0.95,
        cwe="CWE-78",
        supported_languages=["java"],
        remediation="Validate and whitelist command parameters strictly; do not pass raw user input to shell commands.",
        pattern=re.compile(r'(?i)(?:Runtime(?:\.getRuntime\(\))?\.ex' + r'ec|ProcessBuilder)\s*\('),
    ),
    Rule(
        id="JAVA-DESERIAL-001",
        name="Java Insecure Deserialization (XMLDecoder RCE)",
        description="XMLDecoder deserialization can instantiate arbitrary objects and execute commands.",
        category=RuleCategory.DESERIALIZATION,
        severity=Severity.HIGH,
        risk_score=9.8,
        confidence=0.95,
        cwe="CWE-502",
        supported_languages=["java"],
        remediation="Use secure XML parsers with external entity resolution disabled, or use Jackson/Gson.",
        pattern=re.compile(r'(?i)XMLDecoder\s*\('),
    ),
    Rule(
        id="JAVA-SQLI-001",
        name="Java SQL Injection via String Concatenation",
        description="Concatenating variables directly into SQL statement strings.",
        category=RuleCategory.INJECTION,
        severity=Severity.HIGH,
        risk_score=9.0,
        confidence=0.95,
        cwe="CWE-89",
        supported_languages=["java"],
        remediation="Use PreparedStatement with parameterized query binding.",
        pattern=re.compile(r'(?i)(?:executeQuery|executeUpdate)\s*\(\s*["\'].*\+\s*[a-zA-Z0-9_]+'),
    ),

    # PHP
    Rule(
        id="PHP-CMD-001",
        name="PHP Command Execution Vulnerability (system/shell_exec)",
        description="Direct invocation of OS execution functions in PHP.",
        category=RuleCategory.COMMAND_EXECUTION,
        severity=Severity.HIGH,
        risk_score=9.5,
        confidence=0.95,
        cwe="CWE-78",
        supported_languages=["php"],
        remediation="Escape arguments with escapeshellarg()/escapeshellcmd() or use safe PHP standard library APIs.",
        pattern=re.compile(r'(?i)(?:system|shell_ex' + r'ec|passthru|proc_open)\s*\('),
    ),
    Rule(
        id="PHP-DESERIAL-001",
        name="PHP Insecure Object Deserialization (" + "unserialize" + ")",
        description="Deserializing untrusted input can trigger object injection and RCE via magic methods.",
        category=RuleCategory.DESERIALIZATION,
        severity=Severity.HIGH,
        risk_score=9.0,
        confidence=0.95,
        cwe="CWE-502",
        supported_languages=["php"],
        remediation="Use json_decode() for structured data exchange instead of native PHP serialization.",
        pattern=re.compile(r'(?i)' + r'unserialize\s*\('),
    ),

    # C / C++
    Rule(
        id="CPP-BOF-GETS-001",
        name="C/C++ Highly Dangerous Function (" + "get" + "s - Buffer Overflow)",
        description="Unbounded input reading function does not check buffer boundaries.",
        category=RuleCategory.MEMORY_SAFETY,
        severity=Severity.HIGH,
        risk_score=9.8,
        confidence=0.95,
        cwe="CWE-120",
        supported_languages=["c", "cpp"],
        remediation="Replace legacy function with bounded alternatives specifying maximum buffer size.",
        pattern=re.compile(r'\b' + r'gets\s*\('),
    ),
    Rule(
        id="CPP-BOF-STRCPY-001",
        name="C/C++ Insecure Unbounded String Copy (strcpy/strcat Buffer Overflow)",
        description="Unbounded string memory copying leads to buffer overflow vulnerabilities.",
        category=RuleCategory.MEMORY_SAFETY,
        severity=Severity.HIGH,
        risk_score=8.5,
        confidence=0.95,
        cwe="CWE-120",
        supported_languages=["c", "cpp"],
        remediation="Use bounded alternatives like strncpy(), strncat(), or std::string in C++.",
        pattern=re.compile(r'\b(?:strcpy|strcat)\s*\('),
    ),
    Rule(
        id="CPP-FMT-SPRINTF-001",
        name="C/C++ Format String / Buffer Overflow Risk (" + "sprintf" + ")",
        description="Unbounded formatting function does not check target buffer capacity.",
        category=RuleCategory.MEMORY_SAFETY,
        severity=Severity.HIGH,
        risk_score=8.0,
        confidence=0.95,
        cwe="CWE-134",
        supported_languages=["c", "cpp"],
        remediation="Use snprintf() specifying buffer length to prevent buffer overruns.",
        pattern=re.compile(r'(?<![a-zA-Z0-9_])' + r'sprintf\s*\('),
    ),
]

# Suspicious binary artifact rule
BINARY_ARTIFACT_RULE = Rule(
    id="MAL-BIN-ARTIFACT-001",
    name="Suspicious Executable Binary / Script Added",
    description="Compiled binary or executable script introduced in code repository changes.",
    category=RuleCategory.MALWARE,
    severity=Severity.CRITICAL,
    risk_score=9.5,
    confidence=0.95,
    cwe="CWE-506",
    remediation="Verify whether binary artifacts should be compiled from audited source instead of committed directly.",
)

ALL_RULES: List[Rule] = SECRET_RULES + MALWARE_RULES + LANGUAGE_RULES + [BINARY_ARTIFACT_RULE]
RULE_REGISTRY: Dict[str, Rule] = {r.id: r for r in ALL_RULES}
